name: Lint, and breaking change detection
on:
  pull_request:
permissions:
  contents: read
jobs:
  lint-breaking-changes:
    name: Lint, and breaking change detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
      - name: Setup Task
        uses: arduino/setup-task@v1
      - name: Run Buf Checks
        run: task all
